language: c
os: linux
dist: xenial
compiler: gcc
services:
- xvfb
cache:
  pip: true
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.local"
env:
  global:
    - PATH="$HOME/anaconda/bin:$PATH"
    - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
      else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
matrix:
  include:
  - env: FC=gfortran-5
  - env: FC=gfortran-6
  - env: FC=gfortran-7
  - env: FC=gfortran-8
  - env: FC=gfortran-9
before_install:
  - ./travis/before_install.sh
install:
  - ./travis/install.sh
  - ./travis/install_pypack.sh
before_script:
  - ./travis/before_script.sh
script:
  - ./travis/script.sh
notifications:
  slack:
    secure: u8y6K08360InJfEUS3A4B+xxazxeuAbwViRDNnzkuQohFR3rewmzlnrDUSudZQbF4uokpkmQ9/kP8hlwKjrYHHay+4mRgu7ogoWGLnj/KOJjAr04bXuFa8+WOOOSHBjhVhrv86RlApO7/p9HWl2zqINVPl2/UUtnTxYoUnf82EfvYQh9C3hfq6sDAroV1Ei3USk3mpCITuNujHCvAheaBFGX/mElG3JG5TxfZbBQE+srwZTZ5cNT9px76nLfFB2lGKYnjq6WT9miwhIqLv/SJJamGr2an7fHeTtSB4fwETKYxDPhZurWZr4tulp8zUqLN9M9rsND59IJfwo6fV98SZvWSxCMfF31l9Y+n25mZJJFOXqx88glrcNbPLcZQMRG9qFvv8V7S0hpp/1HaMGGWB5gw+h4lrF5cuboatgzMQI6bArESbTNlkUj6TStH0cDw9+jnypPEwa+Ryh6qyq747h9K5duIOZW8DKFB08TAN/PVlmCc5c0HRb6TcEwDRvpOtDnWmsUiKhAhhamN5yfa/6xaXWaJ9aenlJ1lrZVcZkLODYCd52JTHH9CQ51xyXePGBTXVnYne7+7RyG79sXTW2AYvTzAHg8ixs613nrqZV8VyG5y+vKuUrJ61IKab14t9W0lOFDSQoX+pf3YwCkT05K72CHj0chVjrTaWF2Bu4=
